[project]
name = "flux-resolution"
description = "Get the closest compatible flux resolution from a given resolution."
version = "1.0.0"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/iguanesolutions/comfyui-flux-resolution"

[tool.comfy]
PublisherId = "iguanesolutions"
DisplayName = "Flux Resolution"
Icon = ""
